### ISSUE TITLE
Census Upload Error

### ISSUE THREAD

**Issue by groadifer** [associatedemployers/granite#185]
![image](https://user-images.githubusercontent.com/425929/39884300-a7418cba-5446-11e8-9ae0-7de6f7339fad.png)

**Comment by groadifer** [comment]
This is probably already in your Sprint.

**Comment by James1x0** [comment]
Haven't run into issues with this, we have tests for xlsx, but this looks like an error related to the xlsx format:

From AWSEB logs
```
[31merror[39m:  Error: Corrupted zip : can't find end of central directory
    at ZipEntries.readEndOfCentral (/api/node_modules/xlsx/jszip.js:2264:19)
    at ZipEntries.load (/api/node_modules/xlsx/jszip.js:2326:14)
    at new ZipEntries (/api/node_modules/xlsx/jszip.js:2150:14)
    at JSZip.module.exports [as load] (/api/node_modules/xlsx/jszip.js:567:18)
    at new JSZip (/api/node_modules/xlsx/jszip.js:514:14)
    at read_zip (/api/node_modules/xlsx/xlsx.js:12469:24)
    at Object.readSync [as read] (/api/node_modules/xlsx/xlsx.js:12484:21)
    at processExcel (/api/api/employee/index.js:85:30)
    at processExcel.next (<anonymous>)
    at onFulfilled (/api/node_modules/co/index.js:65:19)
```

**Comment by James1x0** [comment]
Igneous is behind on a few releases, we'll retest once we release.
